# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# Skuweld app in the Té Company partner org.

client_id = "a58bd05560ba1d46b50f3b5885f5c9e2"
application_url = "https://skuweld.vercel.app"
embedded = true
name = "Skuweld"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_all_orders,read_inventory,read_locations,read_orders,read_products"

[auth]
redirect_urls = [ "https://skuweld.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
